check50:
  files: &check50_files
    - !exclude "*"
    - !require scores.py
  dependencies:
    - "git+https://github.com/apltools/uva_check50.git#egg=uva.check50>=0.0.2"

submit50:
  files: *check50_files
