check50:
  files: &check50_files
    - !exclude "*"
    - !require sudoku.ipynb
  dependencies:
    - "git+https://github.com/apltools/uva_check50.git#egg=uva.check50>=0.0.3"
    - "jupyter"

submit50:
  files: *check50_files
