check50:
  files: &check50_files
    - !exclude "*"
    - !require climate.ipynb
  dependencies:
    - "jupyter"
    - "git+https://github.com/apltools/uva_check50.git#egg=uva.check50>=0.0.3"


submit50:
  files: *check50_files
